spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blojic
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update